import '@/assets/styles/global.scss'
import MainProvider from '@/providers/MainProvider'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import type { PropsWithChildren } from 'react'

const fontDin = localFont({
	src: [
		{
			path: './fonts/DIN-Light.woff',
			weight: '300',
			style: 'normal',
		},
		{
			path: './fonts/DIN-Light.woff2',
			weight: '300',
			style: 'normal',
		},
		{
			path: './fonts/DIN-Bold.woff',
			weight: '700',
			style: 'normal',
		},
		{
			path: './fonts/DIN-Bold.woff2',
			weight: '700',
			style: 'normal',
		},
	],
	display: 'swap',
	variable: '--font-din',
})

const fontMatthan = localFont({
	src: [
		{
			path: './fonts/Matthan-Regular.woff',
			weight: '400',
			style: 'normal',
		},
		{
			path: './fonts/Matthan-Regular.woff2',
			weight: '400',
			style: 'normal',
		},
	],
	display: 'swap',
	variable: '--font-matthan',
})

const font1 = localFont({
	src: './fonts/Font-1.woff',
	display: 'swap',
	variable: '--font-1',
})

const font2 = localFont({
	src: './fonts/Font-2.woff',
	display: 'swap',
	variable: '--font-2',
})

const font3 = localFont({
	src: './fonts/Font-3.woff',
	display: 'swap',
	variable: '--font-3',
})

const font4 = localFont({
	src: './fonts/Font-4.woff',
	display: 'swap',
	variable: '--font-4',
})

const font5 = localFont({
	src: './fonts/Font-5.woff',
	display: 'swap',
	variable: '--font-5',
})

const font6 = localFont({
	src: './fonts/Font-6.woff',
	display: 'swap',
	variable: '--font-6',
})

const font7 = localFont({
	src: './fonts/Font-7.woff',
	display: 'swap',
	variable: '--font-7',
})

const font8 = localFont({
	src: './fonts/Font-8.woff',
	display: 'swap',
	variable: '--font-8',
})

const font9 = localFont({
	src: './fonts/Font-9.woff',
	display: 'swap',
	variable: '--font-9',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	alternates: {},
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="ru">
			<body
				className={`${fontDin.variable} ${fontMatthan.variable} ${font1.variable} ${font2.variable} ${font3.variable} ${font4.variable} ${font5.variable} ${font6.variable} ${font7.variable} ${font8.variable} ${font9.variable}`}
			>
				<MainProvider>
					<main>{children}</main>
					<div id="modal"></div>
				</MainProvider>
			</body>
		</html>
	)
}
